global using Hukaa.Application.Abstractions.Common;
global using Hukaa.Infrastructure.Common;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Hukaa.Application.Localization;
global using Microsoft.Extensions.Localization;
global using AutoMapper;
global using Hukaa.Application.Abstractions.Services.Auth;
global using Hukaa.Application.DTOs.Auth;
global using Hukaa.Application.DTOs.Wrappers;
global using Hukaa.Domain.Entities.Identities;
global using Microsoft.AspNetCore.Identity;
global using Hukaa.Application.Exceptions;
global using Hukaa.Domain.Consts;
global using Hukaa.Infrastructure.Services.Auth;
global using System.Security.Cryptography;
global using System.Text;
global using Hukaa.Application.Abstractions.Repositories.RefreshTokenRepos;
global using Hukaa.Application.Abstractions.Repositories.UnitOfWork;
global using Hukaa.Domain.Entities.Auth;
global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using Microsoft.IdentityModel.Tokens;
global using Hukaa.Application.Abstractions.Repositories.AuthSessionRepos;
global using Hukaa.Application.DTOs.UserDevice;
global using Microsoft.AspNetCore.Http;
global using System.Text.RegularExpressions;
global using System.Text.Json;
global using Hukaa.Domain.Enums;
global using Hukaa.Application.Abstractions.Services.Account;
global using Hukaa.Application.Abstractions.Services.Profile;
global using Hukaa.Infrastructure.Services.Account;
global using Hukaa.Infrastructure.Services.Profile;
global using Microsoft.EntityFrameworkCore;
global using System.Linq.Expressions;
global using Hukaa.Application.Options.Mail;
global using Hukaa.Application.Abstractions.Services.Mail;
global using Hukaa.Infrastructure.Services.Mail;
global using System.Net;
global using System.Net.Mail;

//--------------
global using IdentityOptions = Hukaa.Application.Options.Identity.IdentityOptions;
global using TokenOptions = Hukaa.Application.Options.Token.TokenOptions;