namespace Tetra.Application.Abstractions.Repositories.Users.UserNotificationSettingsRepositories;

public interface IUserNotificationSettingsWriteRepository : IWriteRepository<UserNotificationSettings>
{
}