namespace Tetra.Application.Abstractions.Repositories.Users.UserNotificationSettingsRepositories;

public interface IUserNotificationSettingsReadRepository : IReadRepository<UserNotificationSettings>
{
}