global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Tetra.Persistence.Context;
global using Tetra.Domain.Entities.Identities;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Tetra.Application.Abstractions.Common;
global using Tetra.Application.Options.Database;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Tetra.Persistence.Configurations;
global using Tetra.Domain.Consts;
global using System.Linq.Expressions;
global using Tetra.Application.Abstractions.Repositories.Base;
global using Tetra.Domain.Entities.Common;
global using Tetra.Application.Abstractions.Repositories.UnitOfWork;
global using Tetra.Domain.Entities.Auth;
global using Tetra.Application.Abstractions.Repositories.Auth.RefreshTokenRepositories;
global using Tetra.Persistence.Repositories.Auth.RefreshTokenRepositories;
global using Tetra.Persistence.Repositories.Base;
global using Tetra.Persistence.Repositories.UnitOfWork;
global using Tetra.Application.Abstractions.Repositories.Auth.AuthSessionRepositories;
global using Tetra.Persistence.Repositories.Auth.AuthSessionRepositories;
global using Tetra.Application.Abstractions.Repositories.Auth.VerificationTokenRepositories;
global using Tetra.Persistence.Repositories.Auth.VerificationTokenRepositories;
global using Tetra.Application.Abstractions.Repositories.Auth.TwoFactorRepositories;
global using Tetra.Persistence.Repositories.Auth.TwoFactorRepositories;
global using Tetra.Domain.Enums;
global using Tetra.Domain.Entities.Users;

// ---------------
global using IdentityOptions = Tetra.Application.Options.Identity.IdentityOptions;
global using TokenOptions = Tetra.Application.Options.Token.TokenOptions;